# Generated by Django 6.0.1 on 2026-02-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('bank', 'Bank'), ('brokerage', 'Brokerage'), ('cash', 'Cash'), ('real_estate', 'Real Estate'), ('crypto', 'Crypto'), ('credit', 'Credit Card'), ('loan', 'Loan'), ('mortgage', 'Mortgage'), ('line_of_credit', 'Line of Credit')], max_length=20),
        ),
    ]
