# Generated by Django 6.0.1 on 2026-04-10 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('income_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cutoff Report',
                'verbose_name_plural': 'Cutoff Reports',
                'ordering': ['-end_date'],
            },
        ),
    ]
